version: "3.9"
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 4000:4000
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres123
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DATABASE=restaurant
    depends_on:
      - db
    links:
      - db:db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./src/backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432

  service_name:
    image: nginx:latest
    container_name: nginx
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    # Comment the command below and the https part of the nginx.conf file when running this for the first time
    # otherwise nginx will crash because it can't execute the command
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    networks:
      - default

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: always
    # This will check if your certificate is up for renewal every 12 hours as recommended by Let’s Encrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
