version: "3.9"
services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres123@db:5432/restaurant
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./src/backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - 5432:5432
