version: "3.9"
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 4000:4000
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres123
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DATABASE=restaurant
    depends_on:
      - db
    links:
      - db:db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./src/backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432

  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - 80:80
      - 443:443
    restart:
      - unless-stopped
    volumes:
      - ./deploy/certbot/conf:/etc/letsencrypt
      - ./deploy/certbot/www:/var/www/certbot
      - ./deploy/nginx.conf:/etc/nginx/
    depends_on:
      - web
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    container_name: "certbot"
    volumes:
      - ./deploy/certbot/conf:/etc/letsencrypt
      - ./deploy/certbot/www:/var/www/certbot
    restart: always
    # This will check if your certificate is up for renewal every 12 hours as recommended by Let’s Encrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
