version: "3.9"
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 4000:4000
    environment:
      # - DATABASE_URL=postgres://postgres:postgres123@db:5432/restaurant
      - PG_USER=postgres
      - PG_PASSWORD=postgres123
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DATABASE=restaurant
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./src/backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
